---
abstract: 'make a hash from @_ and set defaults in subs while checking that all mandatory arguments are present'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-TakeHashArgs
provides:
  Devel::TakeHashArgs:
    file: lib/Devel/TakeHashArgs.pm
    version: 0.006
requires:
  Exporter: 5.58
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.006
